### ISSUE TITLE
Missing commands?

### ISSUE THREAD

**Issue by bombcheck** [winosaure/MilightAPI#3]
Hi there,

I can only see support for switching lights on/off, setting color and brightness. Is this correct? What about the other features? Discomode, Nightmode, Color Temperaturein White-Mode?

Any plans to add these to your API?

**Comment by winosaure** [comment]
Hello,
Sorry to be late to answer.
Yes you are correct, I didn't implemented all commands yet (so far, available command are on/off, settings colors and brightness).

I have plan to add other command such as you mention, but before that I would like to cover the others type of bulbs and make a real use of the factory.

Thank you for your suggestion
